### ISSUE TITLE
Stream Deck Configuration disappear when change focus of application

### ISSUE THREAD

**Issue by mtows** [bitfocus/companion-satellite#107]
I configured my Companion Satellite successfully, but I have a problem. I am using my desktop for other applications like audio cutting... every time I change my window focus to another application the buttons on the connected stream deck disappear... When I then click a button the clicked button appear again. 

It looks like the view is in the background and with clicking the button again the view come to the front. But I don't know why.

Have some one similar problems and have a comfortable solution?

**Comment by Julusian** [comment]
could some other application be trying to use the streamdeck as well as satellite?

**Comment by teuwsenjung** [comment]
It's a good point, will check it soon. Thank you for your input.

**Comment by Julusian** [comment]
I don't think this is the fault of satellite, and there isnt enough info here to look into anything.
Closing until something more is provided which can be acted upon

**Comment by mtows** [comment]
Sorry for my late answer... 

Your suggestion was the solution of my problem. I have an additional application that try to use the stream deck application. 

Problem solved!
