### ISSUE TITLE
failed to start satellite.service - Bitfocus Companion Satellite.

### ISSUE THREAD

**Issue by Lulu2409** [bitfocus/companion-satellite#108]
Hey there,
I've got the following Problem.
I'v flashed the Imagepi to an SD Card and run it on an Raspberry Pi 3 Model B.
it seems to run, but have got a Problem.
Can you help me to solve the Problem?
Thank you very much and best Regads
![Systemctl Status Satellite service](https://github.com/bitfocus/companion-satellite/assets/135103496/ea6a04c7-f995-46b3-bc22-c2abb0f19ab4)

**Comment by Julusian** [comment]
This should be fixed in the v1.6.1 image

**Comment by Lulu2409** [comment]
Thank you very much!
