### ISSUE TITLE
Switch from "master" to "main" breaks update script

### ISSUE THREAD

**Issue by PieterBoeren** [bitfocus/companion-satellite#109]
The recent switch from "master" to "main", breaks the update script (satellite-update):

`Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched.`

I manually fixed it by navigating to `/usr/local/src/companion-satellite` and do a `git checkout main` and re-run the script. This probably should be documented somewhere...

**Comment by Julusian** [comment]
This can be fixed by running the line:
```
sudo sh -c "cd /usr/local/src/companion-satellite && git fetch --all && git reset --hard && git checkout main"
```

Or you can flash the latest image instead, this also means the os will get an update to the latest release.

I don't think it is a good idea to rename the branch back now, so hopefully this command will be sufficient.
