### ISSUE TITLE
Where is the Pi image

### ISSUE THREAD

**Issue by murray484** [bitfocus/companion-satellite#121]
Hello,

I’m having a hard time finding the prebuilt pi image.  I’ve checked the releases tab on GitHub and also on the Bitfocus website.  Can you point me in the right direction? 

Thanks!

**Comment by Julusian** [comment]
It is on the website with the rest of the downloads. The `Linux .img` option

**Comment by murray484** [comment]
I can't believe I didn't see that - thanks!
