### ISSUE TITLE
Pi - Satellite update issue

### ISSUE THREAD

**Issue by khxnv** [bitfocus/companion-satellite#123]
Hello, 
when I try to update on headless pi4 install I keep getting this error... seems something may have moved? Or what am I doing wrong.

pi@satellite:~ $ sudo satellite-update
Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched.

**Comment by Julusian** [comment]
See https://github.com/bitfocus/companion-satellite/issues/109 for help on how to resolve this
