### ISSUE TITLE
Not being able to select the Network Card

### ISSUE THREAD

**Issue by gkasznay** [bitfocus/companion-satellite#128]
I have a wired network for all of my companion stuff, that is not connected to the internet, so i need to connect my computers to the internet with wireless. My satellite keeps changing which network card it is looking at for connecting to my setup. it changes to the other network card even when there is a valid connection on the current one, It changes on about a 2 minute rotation. I would love a way to select the card that is being used for satellite similar to how the main companion app can select one.

**Comment by Julusian** [comment]
This does look like it would be possible for us to support (using the `localAddress` property when opening the connection).
But I have to question whether we should, as this really just sounds like some conflict in network setup.

For reference, in companion the only thing that setting does is change where the admin interface can be accessed from. It has no impact on how connections are made to devices.

Both companion modules and satellite are following the system routing table of your computer. This routing will be updated as you connect/disconnect to networks, but it shouldnt interrupt any existing connections. And the routing table is a series of priority rules to determine what connections should go over which interface.

So the big question is what is causing you to have connection problems with satellite. Is it some network instability causing the network to disconnect and reconnect? Why is that impacting traffic on the other interface?

**Comment by Julusian** [comment]
I don't think there is anything for us to do here, unless someone can argue why this can't be done with routing by the os
