### ISSUE TITLE
No Intel macOS Builds for 1.8.0

### ISSUE THREAD

**Issue by dronenb** [bitfocus/companion-satellite#133]
## Description

I can see there is no published releases for Intel Mac's for 1.8.0. I am not sure why, but if I had to guess it is due to the fact that GitHub changed `macos-latest` to use macOS 14 on Apple Silicon instead of Intel. I imagine the CI to release needs to be fixed to reflect this here: https://github.com/bitfocus/companion-satellite/blob/0025a1f0fdf84fb3f9f64c11f0cb06b86e7c1ae7/.github/workflows/node.yaml#L180-L237

See also: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

**Comment by Julusian** [comment]
Thanks!

I had noticed yesterday that it was missing, but hadn't gotten around to figuring out why it was failing to build.

v1.8.1 is being built now which should succeed for intel macos
