### ISSUE TITLE
Change of Companion IP not persistent

### ISSUE THREAD

**Issue by somebuddy87** [bitfocus/companion-satellite#135]
Hi,
the ip of my companion server changed so i also have to change the ip in my companion satellite.

I tried changing the ip in the webinterface of the satellite.

Webinterface: http://10.87.x.x:9999/

Old Companion Server IP: 192.168.x.x
New Companion Server IP: 10.87.x.x

After changing the IP in the Webinterface the satellite is working until the next reboot. After reboot the companion server to connect to fall back to the old companion server ip.

Is this a bug or an issue or am i doing something wrong?

Version is the latest stable v1.8.1

**Comment by Julusian** [comment]
This could happen if satellite is failing to write the config file (permission issue?) or if you are on pi, perhaps it is failing to update the old config file to clear it after it has 'imported' the config defined there
