### ISSUE TITLE
Installing on Rock Pi S

### ISSUE THREAD

**Issue by sparks-alec** [bitfocus/companion-satellite#139]
Hello! I am attempting to get companion-satellite running on a 512MB PoE Rock Pi S. I've seen these issues where people seem to have it working:
- https://github.com/bitfocus/companion-satellite/issues/76
- https://github.com/bitfocus/companion-satellite/issues/90

But I cannot get it to work for myself.

However, I have gotten close!

With [rock-pi-s_debian_bookworm_cli_b40.img.xz](https://github.com/radxa-build/rock-pi-s/releases/download/b40/rock-pi-s_debian_bookworm_cli_b40.img.xz) from RADXA, I can install companion-satellite using the one-line installer. I can connect to the :9999 web ui just fine. The web UI will connect to the host and show its version. But the Stream Deck never changes from the Elgato logo splash screen and the satellite doesn't show up in the list of Surfaces on the host Companion. Clicking the USB scan button doesn't help. I'm not sure where to go for more debugging info.

With [Armbian_24.5.3_Rockpi-s_bookworm_current_6.6.36_minimal.img.xz](https://dl.armbian.com/rockpi-s/archive/Armbian_24.5.3_Rockpi-s_bookworm_current_6.6.36_minimal.img.xz), I can't perform `sudo satellite-update` as it runs out of space- with many " Cannot write: No space left on device" errors. So I never even get to the web UI. `df -h` reports that my /tmp folder is full. This is the same Armbian version that works for @Keksstar in #90 .

If someone can help me out, I'd be happy to do a full writeup on how to get this working as the Rock Pi is a great form factor for a PoE Stream Deck. Appreciate any help!

**Comment by MeestorX** [comment]
I'm not sure what the minimum sizes are, but I was using a 16G card so I went with:
`fallocate -l 4G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile` and
`mount -o remount,size=2G /tmp/`
While running Armbian bookworm.
That seemed to give the system enough space to install satellite.

**Comment by sparks-alec** [comment]
This worked! Thank you @MeestorX !

**Comment by Keksstar** [comment]
Haven´t used it in a long time, now it isn´t working for me...
@sparks-alec did you use the rock-pi image or the Armbian image? If so, which version? The 6.6.36 Armbian image is gone...
Have you installed Armbian on the RockPi itself or do you use an SD card?

**Comment by sparks-alec** [comment]
I have been using https://github.com/grace-bible/companion-satellite-armbian which builds Rock Pi S compatible .img files automatically. Works great with no fuss.

**Comment by Keksstar** [comment]
> I have been using https://github.com/grace-bible/companion-satellite-armbian which builds Rock Pi S compatible .img files automatically. Works great with no fuss.

THIS is awesome!
Haven´t known about this. Works really well and the build works without any issues :-)
Thank you very much!
