### ISSUE TITLE
Streamdeck Satellite Assuming Control of Stream Deck

### ISSUE THREAD

**Issue by overkill864** [bitfocus/companion-satellite#140]
I have Bitfocus Companion 3.3.1 running on a Mac, then Companion Satellite 2.2.0 running on windows. On companion I have 'Enable Connected Streamdecks' - Disabled. 

I have a Stream Deck XL connected to my windows computer and the companion Satellite is taking it over regardless of that setting being on or off. But its not taking it over fully, its glitching out, attempting to show both the stream deck profile and whatever buttons i have setup in the GUI. Pressing a button the the stream deck literally triggers both, the configured button via the stream deck profile and also that location of the button on the GUI. 

I have restarted companion, satellite, mac, windows, and toggled that setting many times and its producing the same results consistently.

**Comment by overkill864** [comment]
Im also noticing that the companion button plugin doesnt work on the windows computer with Satellite installed either. 

It says
> Connecting To Companion...
> Make sure you have at least Companion version 2.4.0 or newer running on the same machine and that you have enabled support for the Elgato Plugin in the Settings"

Even though the buttons are showing up because the satellite is taking over the stream deck.

**Comment by Julusian** [comment]
Satellite doesn't currently support the plugin, follow https://github.com/bitfocus/companion-satellite/issues/29 for updates if that changes.

The behaviour you are seeing is expected. That  'Enable Connected Streamdecks' setting, is a configuration for companion, not for satellite, so has no effect here.
So yes, if you have both satellite and the elgato software running, then they will fight over the streamdeck.

If you don't want satellite to connect to your streamdecks, what are you using satellite with?
