### ISSUE TITLE
Which protocol Ports ?

### ISSUE THREAD

**Issue by SNRSE** [bitfocus/companion-satellite#22]
hey, i was wondering which ports this app is using is it possible to point it do different ones ?

**Comment by Julusian** [comment]
It connects over TCP 37133.

The port is currently hardcoded as it cannot be changed in companion. What is your reasoning for wanting to change it?

**Comment by SNRSE** [comment]
i use a tool to tunnel the port to a website but then the port is 8080 so if i could change it it would help me  a lot

**Comment by Julusian** [comment]
The next version (0.5, maybe called 1.0) will be using the new satellite api on port 16622, and also allows for choosing a port to connect to
