### ISSUE TITLE
Connecting Reseting

### ISSUE THREAD

**Issue by JPratchett** [bitfocus/companion-satellite#27]
Ver 0.2.2

Single Streamdeck connected over LAN to companion.
Every 60 secs a reconnection seems to occur.

**Comment by Julusian** [comment]
I don't know why this would be happening. Have you checked the companion and companion remote logs to see if any errors are reported?

**Comment by josephdadams** [comment]
@JPratchett are you still experiencing this issue?

**Comment by Julusian** [comment]
There are enough details here to be able to reproduce anything
