### ISSUE TITLE
Error on install Raspberry Pi

### ISSUE THREAD

**Issue by jeremyrmck** [bitfocus/companion-satellite#30]
Hello,

I'm having a heck of a time getting this to run on a headless pi. Can you help? I've installed nodejs, and cloned companion-satellite. Here's the output when I run yarn install...

pi@raspberrypi:~/companion-satellite $ yarn install
yarn install v1.22.15
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "app-builder-bin@3.5.13" is incompatible with requested version "app-builder-bin@3.5.10"
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
[-/8] ⠐ waiting...
[-/8] ⠐ waiting...
[3/8] ⠈ sharp
[4/8] ⠈ usb-detection
error /home/pi/companion-satellite/node_modules/usb-detection: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /home/pi/companion-satellite/node_modules/usb-detection
Output:
prebuild-install WARN install No prebuilt binaries found (target=14.18.1 runtime=node arch=arm libc= platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.18.1 | linux | arm
gyp info find Python using Python version 2.7.16 found at "/usr/bin/python"
gyp http GET https://nodejs.org/download/release/v14.18.1/node-v14.18.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v14.18.1/node-v14.18.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v14.18.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v14.18.1/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/companion-satellite/node_modules/usb-detection/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/.cache/node-gyp/14.18.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/pi/.cache/node-gyp/14.18.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/pi/.cache/node-gyp/14.18.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/pi/companion-satellite/node_modules/usb-detection',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/pi/companion-satellite/node_modules/usb-detection/build'
  CXX(target) Release/obj.target/detection/src/detection.o
../src/detection.cpp: In function ‘void Find(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/detection.cpp:166:68: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
  uv_queue_work(uv_default_loop(), req, EIO_Find, (uv_after_work_cb)EIO_AfterFind);
                                                                    ^~~~~~~~~~~~~
In file included from ../src/detection.h:5,
                 from ../src/detection.cpp:1:
../src/detection.cpp: At global scope:
/home/pi/.cache/node-gyp/14.18.1/include/node/node.h:787:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/pi/.cache/node-gyp/14.18.1/include/node/node.h:821:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/detection.cpp:226:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(detection, init);
 ^~~~~~~~~~~
  CXX(target) Release/obj.target/detection/src/deviceList.o
  CXX(target) Release/obj.target/detection/src/detection_linux.o
../src/detection_linux.cpp:1:10: fatal error: libudev.h: No such file or directory
 #include <libudev.h>
          ^~~~~~~~~~~
compilation terminated.
make: *** [detection.target.mk:111: Release/obj.target/detection/src/detection_linux.o] Error 1
make: Leaving directory '/home/pi/companion-satellite/node_modules/usb-detection/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Linux 5.10.17-v7l+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/companion-satellite/node_modules/usb-detection

Thanks for your assistance!

**Comment by philglenny** [comment]
I had the same problem - solved by installing libudev-dev before doing the yarn install/build:
`apt-get install libudev-dev`

**Comment by Julusian** [comment]
That library has now been replaced, and the new one provides prebuilds for pi
