### ISSUE TITLE
Stream Deck MK2 Panels not recognized

### ISSUE THREAD

**Issue by Jonhug82** [bitfocus/companion-satellite#31]
I have companion remote up and running on a Raspberry PI and it works great with the original 15 button stream decks, however it is not recognizing the MK2 panels - is this an easy fix ?

Thanks

Jonathan

**Comment by McHauge** [comment]
@Jonhug82 For the StreamDeck MK2 you will need to use the 2.2.0 beta releases, you can find a download button just beneath the normal download button

**Comment by McHauge** [comment]
oh sorry this was the companion satellite repo, UPS, please ignore don't know about use with that.

**Comment by Jonhug82** [comment]
Yes the panels are connected ok direct to the machine running Companion but not through the satellite

**Comment by Julusian** [comment]
v0.4.0 does work with the mk2, I have just tested myself to verify.

As you are on a raspberry pi, perhaps you need to update the udev rules as described at https://github.com/julusian/node-elgato-stream-deck#linux

**Comment by Jonhug82** [comment]
Thank you so much for your quick response that works perfectly ! Great application to run alongside Companion
