### ISSUE TITLE
C++ implementation

### ISSUE THREAD

**Issue by alex-Arc** [bitfocus/companion-satellite#32]
Hello
I am going to write a c++ implementation of this  for arduino and stuff
do you want it as a fork of this or some where else?

**Comment by Julusian** [comment]
I think it would be best to start as a project on your own github, it can be easily relocated to the bitfocus organisation later if it is useful to other users.

Unless you need support for 2.1, I would suggest basing another implementation off of https://github.com/bitfocus/companion/wiki/Satellite-API (also used by this branch https://github.com/bitfocus/companion-satellite/tree/feat/satellite-api-v2). The 'old' api will be removed in 2.3, but both are present in 2.2

**Comment by alex-Arc** [comment]
OK
yeah the V2 is way easier.
