### ISSUE TITLE
Local Companion Crashing 2.1.4 (b03d4f0f-2714) [BUG]

### ISSUE THREAD

**Issue by Cmillets** [bitfocus/companion-satellite#35]
I attempting to connect to my host device running 2.1.4 (b03d4f0f-2714). I've changed the ip and included the port. What I'm I doing wrong?

I used the prebuilt installer for mac(V.0.4.0).

Do I need the Stream Deck or Companion softwere running on the remote computer?

Thanks!

**Comment by Cmillets** [comment]
Update! took out for number and it began to connect then disconnect(continuously). 

It caused Companion to crash with the attached error log:
![Screen Shot 2022-01-10 at 4 04 24 PM](https://user-images.githubusercontent.com/48162499/148840197-208d0945-82a1-49fb-b5d5-89d5d2fb8921.png)
It's also holding my three local usb devices hostage:
![Screen Shot 2022-01-10 at 4 13 37 PM](https://user-images.githubusercontent.com/48162499/148840351-6afcd5cd-e054-476e-81c7-eca24db20c32.png)

I have to quit the Satellite application for the errors to stop and everything to work normally on the companion side.

**Comment by Cmillets** [comment]
OS: [Mac 10.14.6 Both Devices]
Browser [Chrome]
Companion Version [2.1.4 (b03d4f0-2714) also downgrade to 2.1.3 and had same issue]

Upon launching Satellite, on the remote device, the local instance of Companion would it began to connect then disconnect(continuously).

It caused Companion to crash with the attached error log:
Screen Shot 2022-01-10 at 4 04 24 PM

It would also hold my three local usb devices hostage:
Screen Shot 2022-01-10 at 4 13 37 PM

To get local companion running normally:

Quit Satellite on remote device
Dismiss error message(many times)
Quite local instance of companion
launch local instance of companion
Disconnect local usb devices
Scan to reconnect local usb devices
This was my first time trying Satellite. It had never run on my remote device or any device(Mac 10.14.6) before. Ip set to Target instance of companion on local device(ie. 192.168.0.130).

Satellite device would show up in control for brief second after it kill the local usb devices then proceed to crash local instance.

**Comment by Julusian** [comment]
This is strange. Not something I've seen in the year ive been running it...
It looks more like a bug in companion than satellite, so lets continue the discussion at https://github.com/bitfocus/companion/issues/1857
