### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by philglenny** [bitfocus/companion-satellite#37]
Having used Companion Satellite (with dropouts) for a while, I've just reinstalled it on a headless pi. I'm now experiencing ECONNREFUSED and can't get the client to connect to the server. Any ideas?

**Comment by Julusian** [comment]
Are you running companion 2.1? The version in master only supports 2.2.
If you do a `git checkout v0.4.0` then you will get the latest version for companion 2.1

**Comment by philglenny** [comment]
I’m running companion 2.2 (one of the many betas!) on the companion server. Any in particular that you suggest?

**Comment by Julusian** [comment]
A recent 2.2 is fine. Try with v0.4.0 of this. It is very possible that I broke something in master for even 2.2, and you likely would have had v0.4.0 previously

**Comment by Julusian** [comment]
@philglenny any update?

**Comment by philglenny** [comment]
Haven't had access to the rig to check - hopefully will later this week

**Comment by Julusian** [comment]
I see no reason for this to be failing if the version of 2.2 is within the last couple of months.
Please retry with the 2.2.0 stable release and make sure that a firewall isnt blocking the connection.
If you are still having the issue after that, then we can reopen this
