### ISSUE TITLE
Received unhandled command: BEGIN

### ISSUE THREAD

**Issue by bryanveloso** [bitfocus/companion-satellite#38]
Using the latest beta build of Companion (2.2.0+3975-beta-37696128) and latest `master` on a Raspberry Pi 3B+.  Running into this error when I run `dev`:

```
pi@satellite:~/companion-satellite $ yarn dev 192.168.88.53
yarn run v1.22.17
$ yarn ts-node src/main.ts 192.168.88.53
$ /home/pi/companion-satellite/node_modules/.bin/ts-node src/main.ts 192.168.88.53
Starting
Connecting to 192.168.88.53:16622
Connected
connected
registerAll []
Received unhandled command: BEGIN CompanionVersion=2.2.0+3975-beta-37696128 ApiVersion=1.1.0
```

So it seems like they're noticing each other, but the satellite isn't displaying in the Surfaces tab.

**Comment by Julusian** [comment]
That error is expected. I didnt bother making it handle that command as this has no use for it. I should probably make it simply log it instead.

It doesnt look like it has found a streamdeck to register with companion, so it is expected to not show up in the surfaces tab

**Comment by bryanveloso** [comment]
Hm, when I downgraded to v0.4.0 it seemed to work fine? I'll give it another shot with the main branch.

**Comment by Julusian** [comment]
Something to look into here is that somewhere in 0.5 it switched the hid backend being used, so it is possible that you need to update the udev rules setup on the pi.

The unhandled commands should now all be handled
