### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by PhilipHamilton** [bitfocus/companion-satellite#41]
From the description I'm just not getting which way around satellite works.
When I run this app, I see no difference in behaviour anywhere.

Anyway, I'm looking for a way to hit/press/click/trigger a stream deck key on a different computer (over the network).
The titles satellite and remote made me wonder if this app might be a solution.

Any help is always appreciated.

**Comment by josephdadams** [comment]
@PhilipHamilton do you still need help with this issue? The general premise is that you would run Companion on one computer, and the Companion Satellite program on the remote computer, which then connects to the primary Companion computer/server. It's a great way to have a physical stream deck located somewhere else but run commands against the primary.

I'll close this issue out but feel free to re open it if you're still needing help.

**Comment by PhilipHamilton** [comment]
Hi Joseph,

Thanks so much for answering back.

So for what you are describing, I am presently using “system" “website” with the URL filled in as http://192.168.1.46:8888/press/bank/1/1 <http://192.168.1.46:8888/press/bank/1/1> or whatever.

How does satellite improve on this functionality?

Philip Hamilton

P. Hamilton Audio Visuals Inc.
320 St-Louis Ave
Pointe Claire, Quebec, H9R 4V9

  (514) 332-6440 (Phone office)
  ***@***.*** (E-mail)

**Comment by josephdadams** [comment]
It sounds like you are using the Elgato software based on that description. Your method just pushes the Companion button remotely.

Using Satellite on another computer would give you button feedback and allow you to access entire pages on the primary Companion server.
