### ISSUE TITLE
Windows 10 Node incompatible

### ISSUE THREAD

**Issue by CCL-DanielLewis** [bitfocus/companion-satellite#44]
I am trying to run on my Windows 10 device and get the following error.

>yarn dist
error companion-satellite@1.0.1: The engine "node" is incompatible with this module. Expected version "^16.14". Got "18.7.0"
error Commands cannot run with an incompatible environment.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Julusian** [comment]
Is there a reason you are building from source instead of using a prebuilt release?

If you do want to continue building from source, you will need to install node 16 instead of node 18. In theory it should work with 18, but I havent verified it works

**Comment by CCL-DanielLewis** [comment]
Because yesterday was pretty much a complete brain fart. Installing normally now. Thanks for being patient with my day long stupidity.

**Comment by josephdadams** [comment]
It happens! No worries
