### ISSUE TITLE
Web Server Configuration Pi Version

### ISSUE THREAD

**Issue by ashjmckenzie** [bitfocus/companion-satellite#45]
Would be great to have a basic network configuration (NIC and Server Pointer) / status webpage for the pi version of Satellite

**Comment by elliotmatson** [comment]
This would be neat, especially if the IP/Port of the ui would display on connected streamdecks when not configured. This would mean we wouldn't need to worry about config files on the boot partition, and companion satellite on an SBC can almost be treated like an appliance.

I'm working on getting the pi version working on Armbian so it can be used on more SBC's, and it doesn't have a FAT32 partition in its stock images, so this would be really helpful

**Comment by Keksstar** [comment]
+1

**Comment by alex-Arc** [comment]
an ip display has been implemented, when the stream deck is in a disconnected state #80
a rest api is also working #78
and i have a pull request open for a very simple webpage #82
