### ISSUE TITLE
Second Stream Deck won't connect: device exists elsewhere

### ISSUE THREAD

**Issue by llamafilm** [bitfocus/companion-satellite#48]
I have two Stream Deck Mini mk.2 and one of them sometimes cannot connect to Companion.
One device is connected to a linux machine running companion-satellite 3b188e2 from git master.  This one remains connected almost all the time.
The other device is connected to a Mac running release version 1.0.1.  This is the one with the problem.  This one always appears in Companion surfaces tab even when I quit the Satellite application.  To fix it I have to restart Companion on the server.
My server is running Companion 2994a6d0 from git master.

**Comment by Julusian** [comment]
I believe this is fixed in companion v2.3.1. There were some issues with companion not detecting satellite clients disconnecting sometimes, which were fixed in that release
