### ISSUE TITLE
internal: Set surface with index to page

### ISSUE THREAD

**Issue by kjetilpp** [bitfocus/companion-satellite#49]
Hello! 

The internal: Set surface with index to page is not working to control satellite devices, is this a known bug? 
internal: Set surface with s/n to page is working just fine. 

Running [v1.0.1](https://github.com/bitfocus/companion-satellite/releases/tag/v1.0.1) on Windows 11 and [2.3.0 (2.3.0+4648-beta-5f8ef99e)](https://bitfocus.io/companion/) on raspberry pi

**Comment by Julusian** [comment]
This wont be anything specific to satellite, this must have broken for non satellite devices too?
