### ISSUE TITLE
 streamdeck-xl: cannot open device on linux

### ISSUE THREAD

**Issue by jasverix** [bitfocus/companion-satellite#52]
On linux companion can see the device, but fails to open it. This works fine on windows.

See issue https://github.com/bitfocus/companion/issues/677 for a better description. It is the same case, it tries to use hidraw3 to connect and fails.

**Comment by Julusian** [comment]
Have you setup the udev rules? https://github.com/bitfocus/companion-satellite/blob/master/pi-image/50-satellite.rules

**Comment by Julusian** [comment]
The beta builds now include a README and udev rules file in the linux build. Sourced from https://github.com/bitfocus/companion-satellite/tree/master/assets/linux

This will be in the 1.5.0 release
