### ISSUE TITLE
Not able to change IP/Port when run as root on macOS

### ISSUE THREAD

**Issue by elliotmatson** [bitfocus/companion-satellite#53]
We are using Satellite on a machine that is used by many people with different user accounts, in a space where sometimes people bring their own machine. Because of this, I'd like Satellite to run before any user has logged in. I've done this in the past with LaunchDaemons running as root, but for some reason I can't get the IP and port arguments to work as root. 

Comparing the logs between running as root vs running as a user, there isn't any "Connecting to xxx.xxx.xxx.xxx:xxxx" line at all, so I'm not sure what the issue is.

Here's the log output from running as root:
```bash
sh-3.2# ./Companion\ Satellite 192.168.50.12 16622
Starting
adding new device: IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS14@14600000/4-Port USB 2.0 Hub@14600000/AppleUSB20Hub@14600000/AppleUSB20HubPort@14610000/Stream Deck Mini@14610000/IOUSBHostInterface@0/AppleUserUSBHostHIDDevice
existing = []
Registering key events for BL44H1B05882
App ready
set tray
objc[7974]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb4846fec8) and /Applications/Companion Satellite.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x112effce0). One of the two will be used. Which one is undefined.
```

**Comment by Julusian** [comment]
The 'desktop' builds of satellite don't support passing the ip and port on the command line like this. They will only read them from the config file. Perhaps you can edit that file to how you want it setup?

Im surprised that it even runs at all, I would have expected it to not be able to open due to being run in the background without a ui

**Comment by elliotmatson** [comment]
I can try that, where is the config file? I couldn't find the location of a config file originally, that's what got me started passing arguments

**Comment by Julusian** [comment]
On my mac, it is at `/Users/julus/Library/Application Support/companion-satellite/config.json`

**Comment by elliotmatson** [comment]
I'll give that a shot, I'll go ahead and close this since it really isn't an intended use case
