### ISSUE TITLE
StreamDeck Mini not woking

### ISSUE THREAD

**Issue by Brewj** [bitfocus/companion-satellite#55]
Hi there we have a Satellite pi running v.1.0.1 on a Rpi4 and the Stream Desk Mini V2.

We have an Original Mk2 which works on that Companion Satellite Pi.  We also have the Original Mk2 running on a Rpi3 but I'm not sure how to double check what version of Companion Satellite I'm running on that one I suspect it might have been pre v1.0.1 as I think we built it prior to July.

How can one check what version we have on a satellite pi and any pointers on why the Mini is not working?

**Comment by Brewj** [comment]
A new image and the update process was a success, is there a -v option?

**Comment by Brewj** [comment]
Ok so I've now tried to recreate this again on a new pi4 however the Mini is not showing up in Companion. the Same mini on my first Pi4 works fine, a StreamDeck standard works fine on both but only the minis work on one Pi, any ideas on what to try?

**Comment by Julusian** [comment]
Oh, it looks like it was supposed to work in v1.0.1, but I think I missed updating the udev rules so it wouldnt work on the pi.
And I forgot to finish the v1.1.0 release, ill collect the builds up now...

**Comment by Julusian** [comment]
https://github.com/bitfocus/companion-satellite/releases/tag/v1.1.0

**Comment by Brewj** [comment]
Excellent is there a way I can update 1.0.1 to that or do I need to do a fresh image?

**Comment by Brewj** [comment]
Cool thank you!
