### ISSUE TITLE
Slow page load

### ISSUE THREAD

**Issue by IVV22** [bitfocus/companion-satellite#56]
Button presses are registered instantly, but when changing pages it does it with a strong delay.
Any tips on how to improve load times of pages?

**Comment by IVV22** [comment]
Hi, sorry

Satelite v.1.1.0
Companion v.2.2.3
platform: RPI 4B
Streamdeck: StreamDeck XL

Works fine on a m1 macbook satelite v.1.1.0

**Comment by IVV22** [comment]
Much beter! 

On the pi 4B it runs great, on the pi 3B also very good but a bit slower.

Thanks!

**Comment by Julusian** [comment]
Great. I shall try and do a v1.1.1 release later today with this fix.

It is expected that the 3B is slower, its a slower cpu and there is a surprising amount of work for the pi to do all at once for the page changes. It has to resize and jpeg-encode the image for each key. At 5ms each, for an xl, that will produce a noticable rolling effect

**Comment by Julusian** [comment]
https://github.com/bitfocus/companion-satellite/releases/tag/v1.2.0

**Comment by respectTheCode** [comment]
This issue is back. When running v1.4.1 pages load very slowly. I downgraded to v1.2.0 and the pages load instantly again.
