### ISSUE TITLE
Button rotation on satellite Stream Decks not working

### ISSUE THREAD

**Issue by sdietz1177** [bitfocus/companion-satellite#57]
Tryin' to rotate buttons CCW or CW on satellite-connected stream deck with no success. Locally added Stream Decks work fine.

**Comment by sdietz1177** [comment]
All versions are in newest releases, both companion and satellite installed on raspberry pi computers (companion on pi4b, satellite on pi3b) with direct images installed.

**Comment by sdietz1177** [comment]
Teste with stream deck models mini and xl

**Comment by Julusian** [comment]
This is fixed in the next beta build 4735
