### ISSUE TITLE
Port

### ISSUE THREAD

**Issue by alias2alias** [bitfocus/companion-satellite#58]
Satellite doesn't seem to connect on different ports other than the default 16622.  I read a post a while back saying this version would allow port changes.  Should you be able to change ports in the current release?  Or is this a consequence of satellite API being fixed at 16622?

**Comment by Julusian** [comment]
It isnt possible to change the port in companion for now. 
But it is possible to use a different port in satellite, to allow for connecting through a router/firewall/gateway that changes the port number.

**Comment by alias2alias** [comment]
That actually is a great solution.  I need to control 1 of 7 machines remotely so I've configured the router to forward 7 different ports to the 7 PCs.  Selecting the port in satellite allows me to change between them quickly.  Thanks.
