### ISSUE TITLE
Two streamdecks connected , only one recognised

### ISSUE THREAD

**Issue by ongenal** [bitfocus/companion-satellite#59]
I have 2 streamdeck XL devices connected to the remote computer (Macbook Pro Intel / Catalina OS)
Companion 2.3.1 on the base computer detect only one stream deck.
And the base computer don't see a local connected stream deck.

**Comment by cpuguru07** [comment]
I have no issues running multiple Stream Deck XL's with Companion on Windows. Do both of the Stream Decks' buttons power on? I had an issue using the built-in USB ports on a Raspberry Pi - the Pi couldn't provide enough power to boot both Stream Decks at the same time. Normally it would work if I waited until after the Pi booted and plugged one in, waited for it to boot, then plugged the other one in. I ended up getting a powered USB hub that provided enough power for both of them.

**Comment by Julusian** [comment]
Elgato released a new revision of various models that required updates. This was done in companion 2.4 and satellite 1.3
