### ISSUE TITLE
Companion Satellite on Pi with Streamdeck +

### ISSUE THREAD

**Issue by virtual-technik** [bitfocus/companion-satellite#65]
Hello everyone, can someone help me?  I want to control a Streamdeck plus via Companion Pi Satellite.  However, it does not recognize the Stremdeck.  Only the Elgato logo comes.  It works fine with other stream decks.  Many thanks for your help.

**Comment by Julusian** [comment]
Could you try the `1.3.1+180` beta build of satellite? It should be fixed in that.

Once you have confirmed it works, I can do a 1.3.2 release
