### ISSUE TITLE
Cant install Companion Satellite headless on Raspberry Pi 4 due to node-hid?

### ISSUE THREAD

**Issue by cooldudelion** [bitfocus/companion-satellite#67]
Hello,
I am atemping to install Companion Satellite headless on a Raspberry Pi 4 4GB
I am using Pi OS Lite 64bit.

Here are the commands I run starting from the moment I touch the Pi:
curl -s https://deb.nodesource.com/setup_16.x | sudo bash
sudo apt update
sudo apt install nodejs -y
wget https://github.com/bitfocus/companion-satellite/archive/refs/heads/master.zip
unzip master.zip
cd companion-satellite-master

curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update && sudo apt install yarn -y

at this point I run, yarn install, and it fails giving me this output:

> liam@raspberrypi1:~/companion-satellite-master $ npm install
> npm WARN deprecated readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs
> npm WARN deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
> npm WARN deprecated electron-osx-sign@0.6.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
> npm WARN deprecated electron-notarize@1.2.2: Please use @electron/notarize moving forward.  There is no API change, just a package name change
> npm ERR! code 1
> npm ERR! path /home/liam/companion-satellite-master/node_modules/node-hid
> npm ERR! command failed
> npm ERR! command sh -c prebuild-install --runtime napi || node-gyp rebuild
> npm ERR! make: Entering directory '/home/liam/companion-satellite-master/node_modules/node-hid/build'
> npm ERR!   CC(target) Release/obj.target/hidapi/hidapi2/libusb/hid.o
> npm ERR! make: Leaving directory '/home/liam/companion-satellite-master/node_modules/node-hid/build'
> npm ERR! prebuild-install WARN install No prebuilt binaries found (target=4 runtime=napi arch=arm64 libc= platform=linux)
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@9.3.1
> npm ERR! gyp info using node@16.20.0 | linux | arm64
> npm ERR! gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
> npm ERR! gyp info spawn /usr/bin/python3
> npm ERR! gyp info spawn args [
> npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
> npm ERR! gyp info spawn args   'binding.gyp',
> npm ERR! gyp info spawn args   '-f',
> npm ERR! gyp info spawn args   'make',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   '/home/liam/companion-satellite-master/node_modules/node-hid/build/config.gypi',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   '/home/liam/.cache/node-gyp/16.20.0/include/node/common.gypi',
> npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
> npm ERR! gyp info spawn args   '-Dvisibility=default',
> npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/liam/.cache/node-gyp/16.20.0',
> npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
> npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/liam/.cache/node-gyp/16.20.0/<(target_arch)/node.lib',
> npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/liam/companion-satellite-master/node_modules/node-hid',
> npm ERR! gyp info spawn args   '-Dnode_engine=v8',
> npm ERR! gyp info spawn args   '--depth=.',
> npm ERR! gyp info spawn args   '--no-parallel',
> npm ERR! gyp info spawn args   '--generator-output',
> npm ERR! gyp info spawn args   'build',
> npm ERR! gyp info spawn args   '-Goutput_dir=.'
> npm ERR! gyp info spawn args ]
> npm ERR! Package libusb-1.0 was not found in the pkg-config search path.
> npm ERR! Perhaps you should add the directory containing `libusb-1.0.pc'
> npm ERR! to the PKG_CONFIG_PATH environment variable
> npm ERR! No package 'libusb-1.0' found
> npm ERR! gyp info spawn make
> npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
> npm ERR! ../hidapi2/libusb/hid.c:47:10: fatal error: libusb.h: No such file or directory
> npm ERR!    47 | #include <libusb.h>
> npm ERR!       |          ^~~~~~~~~~
> npm ERR! compilation terminated.
> npm ERR! make: *** [hidapi.target.mk:111: Release/obj.target/hidapi/hidapi2/libusb/hid.o] Error 1
> npm ERR! gyp ERR! build error
> npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
> npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
> npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
> npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
> npm ERR! gyp ERR! System Linux 5.15.84-v8+
> npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> npm ERR! gyp ERR! cwd /home/liam/companion-satellite-master/node_modules/node-hid
> npm ERR! gyp ERR! node -v v16.20.0
> npm ERR! gyp ERR! node-gyp -v v9.3.1
> npm ERR! gyp ERR! not ok
> 
> npm ERR! A complete log of this run can be found in: /home/liam/.npm/_logs/2023-04-22T02_18_54_578Z-debug-0.log

After that I ran, sudo apt-get install libusb-1.0-0-dev -y, and yarn installed again, It fails but with this error,

> yarn install v1.22.19
> [1/5] Validating package.json...
> [2/5] Resolving packages...
> [3/5] Fetching packages...
> warning Pattern ["node-hid@github:julusian/node-hid#v2.1.2-1","node-hid@^2.1.1","node-hid@^2.1.1","node-hid@^2.1.1"] is trying to unpack in the same destination "/home/liam/.cache/yarn/v6/npm-node-hid-2.1.2-1-a3469ab3a6817a92ec5f96eeefa75ec40a11684d/node_modules/node-hid" as pattern ["node-hid@github:julusian/node-hid#v2.1.2-1"]. This could result in non-deterministic behavior, skipping.
> [4/5] Linking dependencies...
> [5/5] Building fresh packages...
> [6/6] ⠐ electron
> [-/6] ⠐ waiting...
> [-/6] ⠈ waiting...
> [4/6] ⠈ node-hid
> error /home/liam/companion-satellite-master/node_modules/node-hid: Command failed.
> Exit code: 1
> Command: prebuild-install --runtime napi || node-gyp rebuild
> Arguments:
> Directory: /home/liam/companion-satellite-master/node_modules/node-hid
> Output:
> prebuild-install WARN install No prebuilt binaries found (target=4 runtime=napi arch=arm64 libc= platform=linux)
> gyp info it worked if it ends with ok
> gyp info using node-gyp@9.3.1
> gyp info using node@16.20.0 | linux | arm64
> gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
> gyp info spawn /usr/bin/python3
> gyp info spawn args [
> gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
> gyp info spawn args   'binding.gyp',
> gyp info spawn args   '-f',
> gyp info spawn args   'make',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/liam/companion-satellite-master/node_modules/node-hid/build/config.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/liam/.cache/node-gyp/16.20.0/include/node/common.gypi',
> gyp info spawn args   '-Dlibrary=shared_library',
> gyp info spawn args   '-Dvisibility=default',
> gyp info spawn args   '-Dnode_root_dir=/home/liam/.cache/node-gyp/16.20.0',
> gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
> gyp info spawn args   '-Dnode_lib_file=/home/liam/.cache/node-gyp/16.20.0/<(target_arch)/node.lib',
> gyp info spawn args   '-Dmodule_root_dir=/home/liam/companion-satellite-master/node_modules/node-hid',
> gyp info spawn args   '-Dnode_engine=v8',
> gyp info spawn args   '--depth=.',
> gyp info spawn args   '--no-parallel',
> gyp info spawn args   '--generator-output',
> gyp info spawn args   'build',
> gyp info spawn args   '-Goutput_dir=.'
> gyp info spawn args ]
> Package libusb-1.0 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libusb-1.0.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libusb-1.0' found
> make: Entering directory '/home/liam/companion-satellite-master/node_modules/node-hid/build'
> gyp info spawn make
> gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
>   CC(target) Release/obj.target/hidapi/hidapi2/libusb/hid.o
> ../hidapi2/libusb/hid.c:47:10: fatal error: libusb.h: No such file or directory
>    47 | #include <libusb.h>
>       |          ^~~~~~~~~~
> compilation terminated.
> make: *** [hidapi.target.mk:111: Release/obj.target/hidapi/hidapi2/libusb/hid.o] Error 1
> make: Leaving directory '/home/liam/companion-satellite-master/node_modules/node-hid/build'
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
> gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
> gyp ERR! System Linux 5.15.84-v8+
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/liam/companion-satellite-master/node_modules/node-hid

I have also tried,
sudo npm rebuild node-hid
sudo apt install build-essential
uninstalling node-hid via yarn, this does make it yarn install work but yarn build fails.
However they all fail to resolve the issue.
 
Thanks for taking the time to look at my issue and all the best on fixing it.

**Comment by alatteri** [comment]
try this:

```
curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update
sudo apt install -y yarn vim git libudev-dev libusb-1.0-0-dev libgusb-dev nodejs fontconfig gcc g++ make
sudo apt -y dist-upgrade
```

**Comment by Julusian** [comment]
There is a new and simplified instructions in the readme on how to install this onto headless linux, that should work in one simple command.   
I would recommend undoing anything you did to originally install (or start on a fresh pi image), and using the new flow but this could be left until you want to update satellite.

https://github.com/bitfocus/companion-satellite#manual-headless--raspberry-pi
```
curl https://raw.githubusercontent.com/bitfocus/companion-satellite/master/pi-image/install.sh | sh
```

**Comment by cooldudelion** [comment]
Hey Julusian, sorry I didn’t respond at the time but thanks so much! That solved the issue and thanks for now updating that process. Cheers mate!
