### ISSUE TITLE
Failing at the yarn install process

### ISSUE THREAD

**Issue by Brewj** [bitfocus/companion-satellite#70]
Hi there, bit of a noob question here I'm sure, here's the process that I've stepped through.
Hardware Raspberry PiZero W v1.1 with waveshare PoE Hat

Fresh image of raspian

- `sudo apt update`
- `sudo apt full-upgrade`
- `sudo apt install git`
- `git clone https://github.com/bitfocus/companion-satellite`
- `sudo apt install nodejs -y`
- `curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -`
- `echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list`
- `sudo apt install yarn -y`

- `cd companion-satellite/`
- `yarn install`
_00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'_
is the error I've got.

I have also tried 
- `wget https://github.com/bitfocus/companion-satellite/archive/refs/heads/master.zip`
- `unzip master.zip`
- `cd companion-satellite-master`
- `yarn install`
_00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'_
I get the same error.

Could someone be so kind as to tell me where I've gone wrong?

**Comment by Julusian** [comment]
That is not an error I have seen or would expect to see from `yarn`. It looks like you missed running `sudo apt update` after the `echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list` line, so it likely installed the `yarn` package from debian which is a different tool.

-----

There is a new and simplified instructions in the readme on how to install this onto headless linux, that should work in one simple command.   
I would recommend undoing anything you did to originally install (or start on a fresh pi image), and using the new flow which will avoid this issue

https://github.com/bitfocus/companion-satellite#manual-headless--raspberry-pi
```
curl https://raw.githubusercontent.com/bitfocus/companion-satellite/master/pi-image/install.sh | sh
```

**Comment by Brewj** [comment]
Hui Julian, thanks of the speedy response,

partial success please see the report below.

root@rpibrewzero02:~# curl https://raw.githubusercontent.com/bitfocus/companion-satellite/master/pi-image/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1845  100  1845    0     0   7292      0 --:--:-- --:--:-- --:--:--  7292
This will attempt to install Companion Satellite as a system service on this device.
It is designed to be run on headless servers, but can be used on desktop machines if you are happy to not have the tray icon.
A user called 'satellite' will be created to run the service, and various scripts will be installed to manage the service
Adding user `satellite' ...
Adding new group `satellite' (1001) ...
Adding new user `satellite' (1001) with group `satellite' ...
Creating home directory `/home/satellite' ...
Copying files from `/etc/skel' ...
Get:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease [15.0 kB]
Get:2 http://archive.raspberrypi.org/debian bullseye InRelease [23.6 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages [13.2 MB]
Get:4 http://archive.raspberrypi.org/debian bullseye/main armhf Packages [316 kB]
Ign:4 http://archive.raspberrypi.org/debian bullseye/main armhf Packages                                            
Get:4 http://archive.raspberrypi.org/debian bullseye/main armhf Packages [1,227 kB]
Fetched 14.5 MB in 35s (416 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
curl is already the newest version (7.74.0-1.3+deb11u7).
unzip is already the newest version (6.0-26+deb11u1).
The following additional packages will be installed:
  cmake-data git-man libarchive13 liberror-perl libjsoncpp24 librhash0 libudev1 libusb-1.0-doc udev
Suggested packages:
  cmake-doc ninja-build git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk gitweb git-cvs
  git-mediawiki git-svn lrzip
The following NEW packages will be installed:
  cmake cmake-data git git-man libarchive13 liberror-perl libjsoncpp24 librhash0 libudev-dev libusb-1.0-0-dev
  libusb-1.0-doc
The following packages will be upgraded:
  libudev1 udev
2 upgraded, 11 newly installed, 0 to remove and 11 not upgraded.
Need to get 13.9 MB of archives.
After this operation, 63.9 MB of additional disk space will be used.
Get:1 http://archive.raspberrypi.org/debian bullseye/main armhf cmake-data all 3.18.4-2+rpt1+rpi1+deb11u1 [1,726 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf udev armhf 247.3-7+rpi1+deb11u2 [1,431 kB]
Get:6 http://archive.raspberrypi.org/debian bullseye/main armhf cmake armhf 3.18.4-2+rpt1+rpi1+deb11u1 [3,104 kB]   
Get:3 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libudev1 armhf 247.3-7+rpi1+deb11u2 [162 kB]     
Get:4 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libarchive13 armhf 3.4.3-2+deb11u1 [297 kB]    
Get:5 http://mirror.infernocomms.net/raspbian/raspbian bullseye/main armhf libjsoncpp24 armhf 1.9.4-4 [67.0 kB]
Get:7 http://mirror.infernocomms.net/raspbian/raspbian bullseye/main armhf librhash0 armhf 1.4.1-2 [141 kB]
Get:8 http://mirror.infernocomms.net/raspbian/raspbian bullseye/main armhf liberror-perl all 0.17029-1 [31.0 kB]
Get:9 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf git-man all 1:2.30.2-1+deb11u2 [1,828 kB]
Get:10 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf git armhf 1:2.30.2-1+deb11u2 [4,704 kB]
Get:11 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libudev-dev armhf 247.3-7+rpi1+deb11u2 [124 kB]
Get:12 http://mirror.infernocomms.net/raspbian/raspbian bullseye/main armhf libusb-1.0-0-dev armhf 2:1.0.24-3 [70.8 kB]
Get:13 http://mirror.infernocomms.net/raspbian/raspbian bullseye/main armhf libusb-1.0-doc all 2:1.0.24-3 [192 kB]
Fetched 13.9 MB in 3s (4,176 kB/s)   
apt-listchanges: Reading changelogs...
(Reading database ... 43857 files and directories currently installed.)
Preparing to unpack .../udev_247.3-7+rpi1+deb11u2_armhf.deb ...
Unpacking udev (247.3-7+rpi1+deb11u2) over (247.3-7+rpi1+deb11u1) ...
Preparing to unpack .../libudev1_247.3-7+rpi1+deb11u2_armhf.deb ...
Unpacking libudev1:armhf (247.3-7+rpi1+deb11u2) over (247.3-7+rpi1+deb11u1) ...
Setting up libudev1:armhf (247.3-7+rpi1+deb11u2) ...
Selecting previously unselected package cmake-data.
(Reading database ... 43857 files and directories currently installed.)
Preparing to unpack .../00-cmake-data_3.18.4-2+rpt1+rpi1+deb11u1_all.deb ...
Unpacking cmake-data (3.18.4-2+rpt1+rpi1+deb11u1) ...
Selecting previously unselected package libarchive13:armhf.
Preparing to unpack .../01-libarchive13_3.4.3-2+deb11u1_armhf.deb ...
Unpacking libarchive13:armhf (3.4.3-2+deb11u1) ...
Selecting previously unselected package libjsoncpp24:armhf.
Preparing to unpack .../02-libjsoncpp24_1.9.4-4_armhf.deb ...
Unpacking libjsoncpp24:armhf (1.9.4-4) ...
Selecting previously unselected package librhash0:armhf.
Preparing to unpack .../03-librhash0_1.4.1-2_armhf.deb ...
Unpacking librhash0:armhf (1.4.1-2) ...
Selecting previously unselected package cmake.
Preparing to unpack .../04-cmake_3.18.4-2+rpt1+rpi1+deb11u1_armhf.deb ...
Unpacking cmake (3.18.4-2+rpt1+rpi1+deb11u1) ...
Selecting previously unselected package liberror-perl.
Preparing to unpack .../05-liberror-perl_0.17029-1_all.deb ...
Unpacking liberror-perl (0.17029-1) ...
Selecting previously unselected package git-man.
Preparing to unpack .../06-git-man_1%3a2.30.2-1+deb11u2_all.deb ...
Unpacking git-man (1:2.30.2-1+deb11u2) ...
Selecting previously unselected package git.
Preparing to unpack .../07-git_1%3a2.30.2-1+deb11u2_armhf.deb ...
Unpacking git (1:2.30.2-1+deb11u2) ...
Selecting previously unselected package libudev-dev:armhf.
Preparing to unpack .../08-libudev-dev_247.3-7+rpi1+deb11u2_armhf.deb ...
Unpacking libudev-dev:armhf (247.3-7+rpi1+deb11u2) ...
Selecting previously unselected package libusb-1.0-0-dev:armhf.
Preparing to unpack .../09-libusb-1.0-0-dev_2%3a1.0.24-3_armhf.deb ...
Unpacking libusb-1.0-0-dev:armhf (2:1.0.24-3) ...
Selecting previously unselected package libusb-1.0-doc.
Preparing to unpack .../10-libusb-1.0-doc_2%3a1.0.24-3_all.deb ...
Unpacking libusb-1.0-doc (2:1.0.24-3) ...
Setting up libarchive13:armhf (3.4.3-2+deb11u1) ...
Setting up libusb-1.0-doc (2:1.0.24-3) ...
Setting up libusb-1.0-0-dev:armhf (2:1.0.24-3) ...
Setting up liberror-perl (0.17029-1) ...
Setting up udev (247.3-7+rpi1+deb11u2) ...
Setting up libudev-dev:armhf (247.3-7+rpi1+deb11u2) ...
Setting up libjsoncpp24:armhf (1.9.4-4) ...
Setting up librhash0:armhf (1.4.1-2) ...
Setting up git-man (1:2.30.2-1+deb11u2) ...
Setting up cmake-data (3.18.4-2+rpt1+rpi1+deb11u1) ...
Setting up git (1:2.30.2-1+deb11u2) ...
Setting up cmake (3.18.4-2+rpt1+rpi1+deb11u1) ...
Processing triggers for libc-bin (2.31-13+rpt2+rpi1+deb11u5) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for initramfs-tools (0.140) ...
Checking dependencies for the installation script...
Checking availability of curl... OK!
Checking availability of unzip... OK!
Downloading https://github.com/Schniz/fnm/releases/latest/download/fnm-linux.zip...
######################################################################## 100.0%
Installing for Bash. Appending the following to /root/.bashrc:

  # fnm
  export PATH="/opt/fnm:$PATH"
  eval "`fnm env`"

In order to apply the changes, open a new terminal or run the following command:

  source /root/.bashrc
sh: 1: fnm: Exec format error
Cloning into '/usr/local/src/companion-satellite'...
remote: Enumerating objects: 1066, done.
remote: Counting objects: 100% (494/494), done.
remote: Compressing objects: 100% (185/185), done.
remote: Total 1066 (delta 365), reused 408 (delta 305), pack-reused 572
Receiving objects: 100% (1066/1066), 2.15 MiB | 1.26 MiB/s, done.
Resolving deltas: 100% (618/618), done.
./pi-image/update.sh: line 9: /opt/fnm/fnm: cannot execute binary file: Exec format error
./pi-image/update.sh: line 14: /opt/fnm/fnm: cannot execute binary file: Exec format error

**Comment by Brewj** [comment]
Bugger that will do it! Arrrrr

**Comment by Brewj** [comment]
I dusted off a 3b 1.2 success thank you! I did preface this with likely to be a noob question

**Comment by Brewj** [comment]
And success, on a Pi zero 2 W thanks again for your speedy help and support with this.
