### ISSUE TITLE
satellite.service: Failed to load environment files: No such file or directory

### ISSUE THREAD

**Issue by alex-Arc** [bitfocus/companion-satellite#79]
on reboot systemd fails to start satellite again
```
Aug 08 17:22:53 systemd[1]: satellite.service: Failed to load environment files: No such file or directory
Aug 08 17:22:53 systemd[1]: satellite.service: Failed to run 'start' task: No such file or directory
Aug 08 17:22:53 systemd[1]: satellite.service: Failed with result 'resources'.
Aug 08 17:22:53 systemd[1]: Failed to start Bitfocus Companion Satellite.
```
`Failed to load environment files: No such file or directory` seams to reference the config file in  /boot/satellite-config
but that exists

if I run `sudo satellite-update` it stats fine again

**Comment by alex-Arc** [comment]
it works I remove the `EnvironmentFile=/boot/satellite-config` line from the file

**Comment by alex-Arc** [comment]
moving it to `/etc/satellite-config` works for some reason

**Comment by Julusian** [comment]
What distro/image are you running this on? Does it 

the config file is intentionally on the boot partition, as that is typically fat32 so makes it more easily editable from windows/macos without needing to install any drivers for ext.

**Comment by alex-Arc** [comment]
hmm. makes sense.
its an Ubuntu server for arm variant
