### ISSUE TITLE
satellitepi's satellite-help shows companion-edit-config

### ISSUE THREAD

**Issue by commputethis** [bitfocus/companion-satellite#83]
when in the console of satellitepi and one runs `satellite-help` it shows `companion-edit-config` as an option, but it should be `satellite-edit-config`.

**Comment by Julusian** [comment]
Fixed! https://github.com/bitfocus/companion-satellite/commit/ee76c0ccdd6af0bf629ae7c2e2b1059e3bf077f2

**Comment by commputethis** [comment]
Cool, thanks!
