### ISSUE TITLE
skia-canvas failing 'failed to enumerate vulkan phyiscal devices' on older nvidia gpu

### ISSUE THREAD

**Issue by cpuguru07** [bitfocus/companion-satellite#86]
Satellite v1.41 was running just fine. Upgraded to v1.50 and getting this issue. Tried completely uninstalling, rebooting, and reinstalling and still getting same issue. It says Satellite is running, but not in system tray.
![image](https://github.com/bitfocus/companion-satellite/assets/8798041/113752d5-7b55-4971-8c1a-b9c8cd3519c5)

**Comment by Julusian** [comment]
Can you tell me more about your system?

What version and update of windows? (eg win10 22H2)
What GPU do you have, and what version of the drivers?

Are you launching this directly on the machine, or over remote desktop?

**Comment by Julusian** [comment]
From the error it looks to be failing to initialise vulkan on your gpu to do some drawing.
The closest GPU I have is a GT 520, with the same driver version is working without any errors..

I shall see if I can get a build where it is not using vulkan for you, hopefully that will resolve the issue

**Comment by cpuguru07** [comment]
Surprisingly, it looks like it's actually running - no icon in the system tray, but it's pulling icons from Companion and displaying them on the StreamDeck. Unfortunately, I don't have functioning buttons to test button presses with right now.

**Comment by Julusian** [comment]
Yeah, Im not overly surprised that it is semi-working. The library that errored is only used for the status card we show when not connected to companion.
But it would be better if it exited rather than getting stuck in this broken state when something like this happens

**Comment by cpuguru07** [comment]
I reverted to an older version of Satellite on this PC. Working fine on 3 or so others.

**Comment by Julusian** [comment]
Could you give https://builds.julusian.dev/builds/companion-satellite-x64.exe a try?
I have rebuilt the problematic dependency, so hopefully it will work now. I want to double check it helps before pushing it to the builds

**Comment by Julusian** [comment]
@cpuguru07 thanks. I have released that fix as v1.5.2
Hopefully that means this is resolved, if anyone is still having issues let me know and this can be reopened
