### ISSUE TITLE
error /home/satellite/companion-satellite/node_modules/@julusian/skia-canvas: Command failed.

### ISSUE THREAD

**Issue by alatteri** [bitfocus/companion-satellite#88]
```
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning Pattern ["node-hid@npm:@julusian/hid@2.5.0-3","node-hid@^2.1.1","node-hid@^2.1.1","node-hid@^2.1.1"] is trying to unpack in the same destination "/home/satellite/.cache/yarn/v6/npm-node-hid-2.5.0-3-4d0a1aabef8a47b79a3ccdb30fc5b53e8618f5e1-integrity/node_modules/node-hid" as pattern ["node-hid@npm:@julusian/hid@2.5.0-3"]. This could result in non-deterministic behavior, skipping.
info There appears to be trouble with your network connection. Retrying...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
[-/6] ⡀ waiting...
[2/6] ⡀ @julusian/skia-canvas
[-/6] ⡀ waiting...
[4/6] ⡀ electron
error /home/satellite/companion-satellite/node_modules/@julusian/skia-canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install
Arguments: 
Directory: /home/satellite/companion-satellite/node_modules/@julusian/skia-canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.11
node-pre-gyp info using node@18.17.1 | linux | arm
node-pre-gyp info check checked for "/home/satellite/companion-satellite/node_modules/@julusian/skia-canvas/lib/v6/index.node" (not found)
node-pre-gyp http GET https://github.com/Julusian/skia-canvas/releases/download/v1.0.4/linux-arm-napi-v6-glibc.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Julusian/skia-canvas/releases/download/v1.0.4/linux-arm-napi-v6-glibc.tar.gz 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: response status 404 Not Found on https://github.com/Julusian/skia-canvas/releases/download/v1.0.4/linux-arm-napi-v6-glibc.tar.gz
node-pre-gyp ERR! stack     at /home/satellite/companion-satellite/node_modules/@mapbox/node-pre-gyp/lib/install.js:67:15
node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
node-pre-gyp ERR! System Linux 6.1.47-current-sunxi
node-pre-gyp ERR! command "/usr/bin/node" "/home/satellite/companion-satellite/node_modules/@julusian/skia-canvas/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /home/satellite/companion-satellite/node_modules/@julusian/skia-canvas
node-pre-gyp ERR! node -v v18.17.1

```

**Comment by alatteri** [comment]
install script is looking for linux-arm-napi-v6-glibc.tar.gz but the name for the file on github is linux-arm64-napi-v6-glibc.tar.gz

**Comment by Julusian** [comment]
> install script is looking for linux-arm-napi-v6-glibc.tar.gz but the name for the file on github is linux-arm64-napi-v6-glibc.tar.gz

That is a different build for a different cpu architecture. Modern pis (3b, 4 and zero w 2) can run it, if you use the arm64 os image and nodejs.

We don't officially support using arm, but I shall see if I can get arm working

**Comment by alatteri** [comment]
I've been using Satellite on this archicture for a long time, seems to be an issue only with the newer release. 

> > install script is looking for linux-arm-napi-v6-glibc.tar.gz but the name for the file on github is linux-arm64-napi-v6-glibc.tar.gz
> 
> That is a different build for a different cpu architecture. Modern pis (3b, 4 and zero w 2) can run it, if you use the arm64 os image and nodejs.
> 
> We don't officially support using arm, but I shall see if I can get arm working

**Comment by Julusian** [comment]
Well, it worked on previous releases because it was easy to do so (we didnt have to do anything special to make it work). It would be nice to maintain that, so I have tried to get the dependency to compile but have hit a wall as it will require some amount of cross compiling with a rather large dependency tree which is not something I want to figure out

**Comment by alatteri** [comment]
OK...so arm64 is the only arm architecture supported moving forward?

**Comment by Julusian** [comment]
For now yes. I shall think about whether we need to use skia-canvas here, or if we should switch back to sharp. It was changed to allow for simpler drawing code and to be using the same technology as main companion (in the experimental builds). But as having `arm` support here would be nice, maybe that can justify switching back

**Comment by alatteri** [comment]
Thank you for considering the change.  We use a lot of the small/cheap FriendlyArm devices (running ArmbianOS) that are *not* arm64 and are perfect for Companion Satellite.  I'd rather not have to change out all those for more larger expensive devices, but I also understand wanting to simplify things and align with the main Companion codebase.  Can skia-canvas be compiled for arm?

> For now yes. I shall think about whether we need to use skia-canvas here, or if we should switch back to sharp. It was changed to allow for simpler drawing code and to be using the same technology as main companion (in the experimental builds). But as having `arm` support here would be nice, maybe that can justify switching back

**Comment by mitchando96** [comment]
I've just run into the same issue. Can I install an older version with an older script?

**Comment by mitchando96** [comment]
I found this https://skia-canvas.s3.us-east-1.amazonaws.com/v0.9.30/linux-arm-napi-v6-glibc.tar.gz
Can I use this instead?

**Comment by Julusian** [comment]
I may have figured out how to compile that library for arm (technically arm7, will work on most models of pi). But it requires compiling on a pi, so it is going to take many hours.

**Comment by mitchando96** [comment]
Awesome. Please keep us updated. I have my Pi 2B ready :D

**Comment by Julusian** [comment]
OK, I believe this is working now. I have updated my zero w 2 which is running the arm image and it is running happily.  
I had previously held off on updating that pi because of this same reason, although I was planning on fixing it by changing to the arm64 image.

**Comment by mitchando96** [comment]
Thanks @Julusian It has installed and systemctl status satellite reports running. However the Satellite is not appearing in Companion. How do I view the log in this headless installation?

**Comment by Julusian** [comment]
`sudo journalctl -u satellite -e` will show the latest 1000 lines of the log

**Comment by Julusian** [comment]
oh, my fix didnt push last night, try updating again now

**Comment by alatteri** [comment]
confirmed working.  thank you.
