### ISSUE TITLE
Custom icon

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion-satellite#9]
For now I have used the same icons as Companion.

This should be altered in some way or competely replaced to make it more easily identifiable

**Comment by bryce-seifert** [comment]
I can look a making/modifying the icon. I'll also look into if it's possible to have two states for the icon: connected / not connection so you can tell at a glance.

**Comment by Julusian** [comment]
Thanks, that would be a great help.
Yes I like that idea

**Comment by Julusian** [comment]
@bryce-seifert could you try and do it as a vector?

electron-builder complained yesterday that icon.png being only 256x256 was not enough resolution and I was being lazy so upscaled it. But if things are a vector then doing that will be easier and give a much nicer result

**Comment by bryce-seifert** [comment]
Submitted new logo here https://github.com/Julusian/companion-remote/pull/14
I still have the vector file for the main logo if needed as well for changes. Not sure what format would be needed for export

**Comment by bryce-seifert** [comment]
@Julusian Let me know if you need anything else, or have thoughts for the logo / menu bar icon

**Comment by Julusian** [comment]
Finally got around to dealing with this, using the logo from https://github.com/bitfocus/bitfocus-icons/tree/main/Companion%20Satellite
