### ISSUE TITLE
not opening in windows

### ISSUE THREAD

**Issue by ikami75** [bitfocus/companion-satellite#94]
v 1.5 and 1.5.1 have a java script error in windows 11 will not start.

**Comment by ikami75** [comment]
1.41 installs and opens just fine

**Comment by xyzvideo** [comment]
same

![image](https://github.com/bitfocus/companion-satellite/assets/82725789/77560a2b-6c0b-4177-9d7d-0617ad3c030e)

**Comment by Julusian** [comment]
Sounds like this is a duplicate of #86

I have an idea on a fix, should be posting with an update in that issue soon
