### ISSUE TITLE
Windows 10 Fatal Error

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion-satellite#98]
on new computer with fresh install of Windows 10 it crashed after install and try to run. Check the image
![Satelite crash](https://github.com/bitfocus/companion-satellite/assets/22023099/26881fea-8431-4d02-b385-9d27b9ef3336)

**Comment by Julusian** [comment]
Try installing the vcruntime https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by Julusian** [comment]
This is fixed in v1.5.5
